In [1]:
!pip install tensorflow-gpu

     |████████████████████████████████| 489.6 MB 28 kB/s 


In [2]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

In [3]:
tf.__version__

'2.7.0'

# Dataset preprocessing

In [4]:
#Loading the Fashion Mnist dataset
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


#Image Normalization

We devide each image in the training and testing dataset with the maxiumum number of pixels (255).

In this way each pixel will be in the rainge [0, 1]. By normalizing images we are making sure that our model (ANN) trains faster.

In [5]:
X_train = X_train / 255.0
X_test = X_test / 255.0

# Reshaping of the dataset

Since we are using fully connected network, we reshape the training and testing subsets to be in the vector format.

In [6]:
X_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [7]:
#Since each image is 28x28, we simply use reshape the full dataset to [-1 (all elements), height * width]
X_train = X_train.reshape(-1, 28*28)

In [8]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
X_train.shape

(60000, 784)

In [10]:
X_test

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [11]:
X_test.shape

(10000, 28, 28)

In [12]:
#Reshape the testing subset in the same way
X_test = X_test.reshape(-1, 28*28)

In [13]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
X_test.shape

(10000, 784)

# ANN

Sequential model

In [15]:
model = tf.keras.models.Sequential()

Dense Layer

In [16]:
model.add(tf.keras.layers.Dense(units=128,activation='relu',input_shape=(784,)))

Dropout layer

For reducing the chances of Overfitting

In [17]:
model.add(tf.keras.layers.Dropout(0.2))

The second dense layer for the output

In [18]:
model.add(tf.keras.layers.Dense(units=10,activation='softmax'))

Compile the model

In [19]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['sparse_categorical_accuracy'])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               100480    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


Model training

In [21]:
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.5277 - sparse_categorical_accuracy: 0.8135
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3996 - sparse_categorical_accuracy: 0.8556
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3647 - sparse_categorical_accuracy: 0.8680
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3410 - sparse_categorical_accuracy: 0.8745
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3282 - sparse_categorical_accuracy: 0.8803


# Model evaluation and prediction

In [22]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.3538 - sparse_categorical_accuracy: 0.8695


In [23]:
print("Test accuracy: {}".format(test_accuracy))

Test accuracy: 0.8694999814033508


# Saving the model

In [24]:
model_json = model.to_json()
with open("fashion_model.json", "w") as json_file:
    json_file.write(model_json)

# Saving network weights

In [25]:
model.save_weights("fashion_model.h5")

In [26]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=32, activation='relu', input_shape=(784, )))
model.add(tf.keras.layers.Dropout(0.4))
model.add(tf.keras.layers.Dense(units=64, activation='relu'))
model.add(tf.keras.layers.Dropout(0.6))
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dense(units=10, activation='softmax'))

In [27]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [28]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 32)                25120     
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense_3 (Dense)             (None, 64)                2112      
                                                                 
 dropout_2 (Dropout)         (None, 64)                0         
                                                                 
 dense_4 (Dense)             (None, 128)               8320      
                                                                 
 dense_5 (Dense)             (None, 10)                1290      
                                                                 
Total params: 36,842
Trainable params: 36,842
Non-trai

In [29]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 3s 2ms/step - loss: 1.0742 - sparse_categorical_accuracy: 0.5809
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.8379 - sparse_categorical_accuracy: 0.6766
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7971 - sparse_categorical_accuracy: 0.6932
Epoch 4/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7648 - sparse_categorical_accuracy: 0.7057
Epoch 5/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7428 - sparse_categorical_accuracy: 0.7137
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7333 - sparse_categorical_accuracy: 0.7188
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7245 - sparse_categorical_accuracy: 0.7227
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.7045 - sparse_categorical_accuracy: 0.7300
Epoch 9/10
1875/1875 [==========

In [30]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.5940 - sparse_categorical_accuracy: 0.7622
